 ° ± ² ³ ´ µ ¶ · ¸ ¹ º » ¼ ½ ¾ ¿ À Á Â Ã Ä Å Æ Ç È É Ê Ë Ì Í Î Ï Ğ Ñ Ò Ó Ô Õ Ö × Ø Ù Ú Û Ü İ Ş ß 
10 
 7fÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´ 74Help Screen7f ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ70¿10
 7f³70                                                                            ³10
 7f³70                   Press any key to return to main screen                   ³10
 7f³70                                                                            ³10
 7f³70  If your native language is not available during installation, select      ³10
 7f³70  English (USA). At end of installation you will be proposed to change it.  ³10
 7f³70                                                                            ³10
 7f³70  If you need to append kernel parameters to the command line to boot your  ³10
 7f³70  system, type them in the main screen after "Extra parameters: ".          ³10
 7f³70  In case of black screen after booting, try this parameter:   79nomodeset70    ³10
 7f³70                                                                            ³10
 7f³70  You need to append kernel parameters and do not use an US keyboard?       ³10
 7f³70  Don't panic! To find the key you need to press to print some character,   ³10
 7f³70  visit the web page http://slint.fr/en/kbd.svg                             ³10
 7f³70                                                                            ³10
 7f³70                                                                            ³10
 7f³70  For more help, visit http://www.salixos.org/                              ³10
 7f³70                                                                            ³10
 7fÀ70ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ10
