 ° ± ² ³ ´ µ ¶ · ¸ ¹ º » ¼ ½ ¾ ¿ À Á Â Ã Ä Å Æ Ç È É Ê Ë Ì Í Î Ï Ğ Ñ Ò Ó Ô Õ Ö × Ø Ù Ú Û Ü İ Ş ß  
10
 7fÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´ 74Installation of Salix 14.2 (64-bit)7f ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ70¿10
 7f³70                                                                            ³10
 7f³70 Select the language for installation with the arrow keys, enter extra      ³10
 7f³70 parameters at the prompt if need be and press [Enter] to boot.             ³10
 7f³70                                                                            ³10
 7f³70            ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ7f¿70              ³10
 7f³70            ³70          This is where the menu goes           7f³70             ³10
 7f³70            ³701e               (active colour)                  7f³70              ³10
 7f³70            ³70              (inactive colour)                 7f³70              ³10
 7f³70            ³70              (inactive colour)                 7f³70              ³10
 7f³70            ³70              (inactive colour)                 7f³70              ³10
 7f³70            ³70              (inactive colour)                 7f³70              ³10
 7f³70            ³70              (inactive colour)                 7f³70              ³10
 7f³70            ³70              (inactive colour)                 7f³70              ³10
 7f³70            ³70              (inactive colour)                 7f³70              ³10
 7f³70            ³70              (inactive colour)                 7f³70              ³10
 7f³70            ³70                                                1e7f³70             ³10
 7f³70            À7fÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ70              ³10
 7f³70                                                                            ³10
 7f³70 Extra parameters: 35                                                     70    ³10
 7f³70                                                                            ³10
 7f³70 Press [71F170] for help                                                        ³10
 7fÀ70ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ10
