#!/bin/sh
export TEXTDOMAIN=salix-installer
. gettext.sh
TMP=/var/log/setup/tmp
if [ ! -d $TMP ]; then
	mkdir -p $TMP
fi

. /usr/lib/setup/INCISO

while [ 0 ]; do
	rm -f $TMP/SeTDS $TMP/SeTmount $TMP/SeTsource

	umount -f /var/log/mount 2>/dev/null
	if [ -n "$(mount | grep /var/log/mount)" -o -d /var/log/mount/lost+found -o -d /var/log/mount/recycled -o -r /var/log/mount/io.sys ]; then
		echo "" > $TMP/tempmsg
		gettext "Setup failed to unmount a required directory:" >> $TMP/tempmsg
		echo "" >> $TMP/tempmsg
		echo "/var/log/mount" >> $TMP/tempmsg
		echo "" >> $TMP/tempmsg
		gettext "Please reboot the machine and try again." >> $TMP/tempmsg
		echo "" >> $TMP/tempmsg
		dialog \
		  --title "`gettext "ERROR"`" \
		  --yes-label "`gettext "REBOOT"`" \
		  --no-label "`gettext "CANCEL"`" \
		  --yesno "$(cat $TMP/tempmsg)" \
		  0 0
		RET=$?
		rm -f $TMP/tempmsg
		if [ $RET -eq 0 ]; then
			reboot
		else
			exit 1
		fi
	fi

	while [ 0 ]; do
		echo "" > $TMP/tempmsg
		gettext "Please provide the path to a directory containing the \
contents (or an ISO image) of a Salix installation disc." \
			>> $TMP/tempmsg
		echo "" >> $TMP/tempmsg
		gettext "Note: You may use any directory within the current filesystem \
except '/mnt' or '/var/log/mount' as these are required by \
setup." \
 			>> $TMP/tempmsg
		dialog \
		  --title "`gettext "SELECT A PRE-MOUNTED DIRECTORY"`" \
		  --help-button --help-label "`gettext "Browse"`" \
		  --inputbox "$(cat $TMP/tempmsg)" \
		  0 0 \
		  $SOURCEDIR \
		  2> $TMP/sourcedir
		RET=$?
		SOURCEDIR="$(cat $TMP/sourcedir)"
		rm -f $TMP/sourcedir $TMP/tempmsg
		if [ $RET -eq 2 ]; then
			if [ -z "$SOURCEDIR" -o ! -d "$SOURCEDIR" ]; then
				SOURCEDIR=/
			fi
			dialog \
			  --title "`gettext "SELECT A DIRECTORY"`" \
			  --dselect $SOURCEDIR \
			  0 0 \
			  2> $TMP/sourcedir
			SOURCEDIR="$(cat $TMP/sourcedir)"
			rm -f $TMP/sourcedir $TMP/tempmsg
			continue
		elif [ $RET -ne 0 ]; then
			exit 1
		fi
		break
	done

	SOURCEDIR="$(echo "$SOURCEDIR" | sed 's|/$||')"

	mkdir -p /var/log/mount 2>/dev/null
	check_iso_image $SOURCEDIR
	if [ $? -eq 0 ]; then
		if [ -d /var/log/mount/salix ]; then
			echo "/var/log/mount/salix" > $TMP/SeTDS
		else
			SRCISO=$(basename $SOURCEISO)
			gettext "The ISO image you specified is not valid:" > $TMP/tempmsg
			echo "" >> $TMP/tempmsg
			echo "$SRCISO" >> $TMP/tempmsg
			echo "" >> $TMP/tempmsg
			gettext "Please check and try again." >> $TMP/tempmsg
			dialog \
			  --title "`gettext "INVALID ISO IMAGE"`" \
			  --exit-label "`gettext "OK"`" \
			  --textbox "$TMP/tempmsg" \
			  0 0
			rm -f $TMP/tempmsg
			continue
		fi
	elif [ -d $SOURCEDIR/salix -a -f $SOURCEDIR/PACKAGES.TXT.gz ]; then
		rm -f /var/log/mount 2>/dev/null
		rmdir /var/log/mount 2>/dev/null
		ln -sf $SOURCEDIR /var/log/mount
		echo "/var/log/mount/salix" > $TMP/SeTDS
	elif [ -d $SOURCEDIR/core -a -d $SOURCEDIR/basic -a -d $SOURCEDIR/full ]; then
		rm -f /var/log/mount 2>/dev/null
		rmdir /var/log/mount 2>/dev/null
		ln -sf $SOURCEDIR /var/log/mount
		echo "/var/log/mount" > $TMP/SeTDS
	else
	gettext "The directory you specified is not valid:" \
		> $TMP/tmpmsg
	echo "" >> $TMP/tmpmsg
	echo "$SOURCEDIR" >> $TMP/tmpmsg
	echo "" >> $TMP/tmpmsg
	gettext "Please check and try again." >> $TMP/tmpmsg
	echo "" >> $TMP/tmpmsg
		dialog \
		  --title "`gettext "INVALID SOURCE DIRECTORY"`" \
		  --exit-label "`gettext "OK"`" \
		  --textbox "$TMP/tempmsg" \
		  0 0
		rm -f $TMP/tempmsg
		continue
	fi
	echo "-source_mounted" > $TMP/SeTmount
	echo "/dev/null" > $TMP/SeTsource
	break
done
