#!/bin/sh
export TEXTDOMAIN=salix-installer
. gettext.sh
TMP=/var/log/setup/tmp
if [ ! -d $TMP ]; then
	mkdir -p $TMP
fi

. /usr/lib/setup/INCISO

while [ 0 ]; do
	rm -f $TMP/SeTDS $TMP/SeTmount $TMP/SeTsource

	umount -f /var/log/mount 2>/dev/null
	if [ -n "$(mount | grep /var/log/mount)" -o -d /var/log/mount/lost+found -o -d /var/log/mount/recycled -o -r /var/log/mount/io.sys ]; then
		echo "" > $TMP/tempmsg
		gettext "Setup failed to unmount a required directory:" >> $TMP/tempmsg
		echo "" >> $TMP/tempmsg
		echo "/var/log/mount" >> $TMP/tempmsg
		gettext "Please reboot the machine an try again." >> $TMP/tempmsg
		echo "" >> $TMP/tempmsg
		dialog \
		  --title "`gettext "ERROR"`" \
		  --yes-label "`gettext "REBOOT"`" \
		  --no-label "`gettext "CANCEL"`" \
		  --yesno "$(cat $TMP/tempmsg)" \
		  11 70
		RET=$?
		rm -f $TMP/tempmsg
		if [ $RET -eq 0 ]; then
			reboot
		else
			exit 1
		fi
	fi

	while [ 0 ]; do
		echo "" > $TMP/tempmsg
		gettext "Please specify which partition on your hard disk or \
USB stick contains the contents (or an ISO image) of a Salix \
installation disc." >> $TMP/tempmsg
		echo "" >> $TMP/tempmsg
		gettext "Example:" >> $TMP/tempmsg
		echo " /dev/sdb2" >> $TMP/tempmsg
		gettext "Note: Use the <Partitions> button to list available partitions." >> $TMP/tempmsg
		echo "" >> $TMP/tempmsg
		dialog \
		  --title "`gettext "SELECT HARD DISK PARTITION"`" \
		  --help-button --help-label "`gettext "Partitions"`" \
		  --inputbox "$(cat $TMP/tempmsg)" \
		  16 70 \
		  $SOURCEDEV \
		  2> $TMP/sourcepart
		RET=$?
		SOURCEDEV="$(cat $TMP/sourcepart)"
		rm -f $TMP/tempmsg $TMP/sourcepart
		if [ $RET -eq 2 ]; then
			echo "   Device Boot      Start         End      Blocks   Id  System" > $TMP/tempmsg
			fdisk -l 2>/dev/null | grep "^/dev" | sort >> $TMP/tempmsg
			dialog \
			  --title "`gettext "PARTITIONS LIST"`" \
			  --textbox "$TMP/tempmsg" \
			  0 0
			rm -f $TMP/tempmsg
			continue
		elif [ $RET -ne 0 ]; then
			exit 1
		fi
		break
	done

	if [ -n "$(mount | grep $SOURCEDEV)" ]; then
		rm -f /var/log/mount 2>/dev/null
		rmdir /var/log/mount 2>/dev/null
		ln -sf $(mount | grep $SOURCEDEV | cut -f 3 -d ' ') /var/log/mount
		RET=0
	else
		mkdir -p /var/log/mount 2>/dev/null
		mount -r $SOURCEDEV /var/log/mount 2>/dev/null
		RET=$?
	fi

	if [ $RET -ne 0 ]; then
gettext "
Failed to mount hard disk partition:

$SOURCEDEV

Please check and try again.
" > $TMP/tempmsg
		dialog \
		  --title "`gettext "MOUNT FAILURE"`" \
		  --exit-label "`gettext "OK"`" \
		  --textbox "$TMP/tempmsg" \
		  0 0
		rm -f $TMP/tempmsg
		continue
	else
gettext "
Successfully mounted hard disk partition:

$(mount | grep $SOURCEDEV)

" > $TMP/tempmsg
		dialog \
		  --title "`gettext "MOUNT SUCCESS"`" \
		  --exit-label "`gettext "OK"`" \
		  --textbox "$TMP/tempmsg" \
		  0 0
		rm -f $TMP/tempmsg
	fi

	while [ 0 ]; do
		echo "" > $TMP/tempmsg
		gettext "Now please provide the path to a directory containing \
the contents (or an ISO image) of a Salix installation disc." >> $TMP/tempmsg
		echo "" >> $TMP/tempmsg
		gettext "Note: The path you enter must be relative to the \
mount point. So, '/var/log/mount/salix-xfce' should be entered \
as '/salix-xfce'." >> $TMP/tempmsg
		echo "" >> $TMP/tempmsg
		dialog \
		  --title "`gettext "SELECT SOURCE DIRECTORY"`" \
		  --help-button --help-label "`gettext "Browse"`" \
		  --inputbox "$(cat $TMP/tempmsg)" \
		  14 70 \
		  $SOURCEDIR \
		  2> $TMP/sourcedir
		RET=$?
		SOURCEDIR="$(cat $TMP/sourcedir)"
		rm -f $TMP/sourcedir $TMP/tempmsg
		if [ $RET -eq 2 ]; then
			if [ -z "$SOURCEDIR" -o ! -d "/var/log/mount$SOURCEDIR" ]; then
				SOURCEDIR="/"
			fi
			dialog \
			  --title "`gettext "SELECT A DIRECTORY"`" \
			  --dselect "/var/log/mount$SOURCEDIR" \
			  12 80 \
			  2> $TMP/sourcedir
			SOURCEDIR="$(cat $TMP/sourcedir | sed 's|^/var/log/mount||')"
			rm -f $TMP/sourcedir $TMP/tempmsg
			continue
		fi
		break
	done
	
	if [ $RET -ne 0 ]; then
		continue
	fi

	SRCDIR="$(echo "/var/log/mount$SOURCEDIR" | sed 's|/$||')"
	
	check_iso_image $SRCDIR /var/log/mntiso
	if [ $? -eq 0 ]; then
		if [ -d /var/log/mntiso/salix ]; then
			echo "/var/log/mntiso/salix" > $TMP/SeTDS
		else
SRCISO=$(basename $SOURCEISO)
gettext "
The ISO image you specified is not valid:

$SRCISO

Please check and try again.
" > $TMP/tempmsg
			dialog \
			  --title "`gettext "INVALID ISO IMAGE"`" \
			  --exit-label "`gettext "OK"`" \
			  --textbox "$TMP/tempmsg" \
			  0 0
			rm -f $TMP/tempmsg
			umount -f /var/log/mntiso 2>/dev/null
			continue
		fi
	elif [ -d $SRCDIR/salix -a -f $SRCDIR/PACKAGES.TXT.gz ]; then
		echo "$SRCDIR/salix" > $TMP/SeTDS
	elif [ -d $SRCDIR/core -a -d $SRCDIR/basic -a -d $SRCDIR/full ]; then
		echo "$SRCDIR" > $TMP/SeTDS
	else
		gettext "The directory you specified is not valid:" > $TMP/tempmsg
		echo "" >> $TMP/tempmsg
		echo "$SOURCEDIR" >> $TEMP/tempmsg
		echo "" >> $TMP/tempmsg
		gettext "Please check and try again." >> $TMP/tempmsg
		dialog \
		  --title "`gettext "INVALID SOURCE DIRECTORY"`" \
		  --exit-label "`gettext "OK"`" \
		  --textbox "$TMP/tempmsg" \
		  0 0
		rm -f $TMP/tempmsg
		continue
	fi
	echo "-source_mounted" > $TMP/SeTmount
	echo "/dev/null" > $TMP/SeTsource
	break
done
