#!/bin/sh
export TEXTDOMAIN=salix-installer
dglist=""
n=0
for dev in "$( cat /proc/partitions \
	| grep -v '^$' \
	| grep -v 'name' \
	| grep -v 'ram' \
	| grep -v 'loop' \
	| grep -v 'sr[0-9]' \
	| sed -e 's/^[ \t]*[0-9]*[ \t]*[0-9]*[ \t]*[0-9]*[ \t]*\(\([a-z]*\)[0-9]*[^0-9]*\|\([a-z\/]*[0-9]*[a-z]*[0-9]*\).*\)$/\2\3 disk \"\"/' | sort -u )" ; do

	dglist="$dglist $dev"
#	n=$(($n+1))
done


DISK=$(dialog \
--stdout \
--visit-items \
--ok-label "`gettext "Go"`" \
--cancel-label "`gettext "Exit"`" \
--title "`gettext "PARTITIONS EDITOR"`" \
--radiolist "`gettext "Welcome to the Salix partition editor. Press <SPACE> to \
select a disk and select Go to start partitioning. If you don't want to \
alter the partition layout, select Exit."`

`gettext "NOTE: If you are planning to use BTRFS for your / \
filesystem, LILO the default boot loader will not be able to boot it. \
In that case, you will need a separate /boot partition with another \
filesystem."`

`gettext "You usually need at least 2 partitions:"`
- `gettext "1 LINUX bootable partition (10GB minimum recommended)"`
- `gettext "1 SWAP partition (1GB minimum recommended)"`:" \
0 0 0 ${dglist} )
# $(($n+12)) 75 $(($n+1)) ${dglist} )

if [ ! "${DISK}" ]; then
	 exit 0
fi
clear
DISKCMD=cfdisk
if LANG=C fdisk -l /dev/${DISK} 2> /dev/null | grep -q "Disklabel type: gpt" ; then
	DISKCMD=cgdisk
else
	modprobe efivars > /dev/null 2>&1 # will do nothing on non-EFI system
	[ -e /sys/firmware/efi/efivars ] && DISKCMD=cgdisk
fi
$DISKCMD /dev/${DISK} 2>/dev/null
