#!/bin/sh
export TEXTDOMAIN=salix-installer
TMP=/var/log/setup/tmp
if [ ! -d $TMP ]; then
	mkdir -p $TMP
fi

while [ 0 ]; do
dialog \
--visit-items \
--backtitle "`gettext "Select Salix installation source."`" \
--title "`gettext "SOURCE MEDIA SELECTION"`" \
--menu \
"`gettext "Please select the media from which to install Salix Linux:"`" \
14 80 7 \
"1" "`gettext "Install from a Salix USB stick"`" \
"2" "`gettext "Install from a Salix CD or DVD"`" \
"3" "`gettext "Install from a hard drive partition"`" \
"4" "`gettext "Install from a pre-mounted directory"`" \
"5" "`gettext "Install from FTP/HTTP server"`" \
"6" "`gettext "Install from NFS (Network File System)"`" \
"7" "`gettext "Install from a Samba share"`" \
2> $TMP/media
	RET=$?
	SOURCE_MEDIA="$(cat $TMP/media)"
	rm -f $TMP/media
	if [ $RET -ne 0 ]; then
		rm -f $TMP/SeTDS $TMP/SeTmount $TMP/SeTsource
		exit 1
	fi

	test_ret() {
		if [ $? -ne 0 ]; then
			continue
		fi
	}

	case "$SOURCE_MEDIA" in
		"1") INSUSB ; test_ret ;;
		"2") INSCD ; test_ret ;;
		"3") INShd ; test_ret ;;
		"4") INSdir ; test_ret ;;
		"5") INSURL ; test_ret ;;
		"6") INSNFS ; test_ret ;;
		"7") INSSMB ; test_ret ;;
	esac

	break
done
