#!/bin/sh
export TEXTDOMAIN=salix-installer
TMP=/var/log/setup/tmp
if [ ! -d $TMP ]; then
  mkdir -p $TMP
fi
# If the distribution source is already known, we can avoid listing
# stuff that isn't there.
if [ ! -r $TMP/SeTT_PX -o ! -r $TMP/SeTDS ]; then
  unset T_PX
  unset DS
else
  T_PX="`cat $TMP/SeTT_PX`"
  DS="`cat $TMP/SeTDS`"
fi
# In /usr/lib/setup/slackinstall, $TMP/series is a directory.
# Depending on how you use the 'setup' script, you can end up going
# round in circles due to this script using 'series' as a text file but
# not being able delete it due to an rm -f.  Now we use rm -rf.
# It's a toss up between accidentally wiping the series selection
# (it only takes a few seconds to re-select the stuff) and getting
# confused.
rm -rf $TMP/SeTSERIES $TMP/tmpscript $TMP/series 

echo -n 'dialog --visit-items --backtitle "' > $TMP/tmpscript
gettext "Selecting software to install." >> $TMP/tmpscript
echo -n '" --title "' >> $TMP/tmpscript
gettext "PACKAGE SERIES SELECTION" >> $TMP/tmpscript
echo -n '" --item-help --output-separator "#" --checklist "' >> $TMP/tmpscript
gettext "Now it is time to select which general categories of software \
to install on your system. \
Use the spacebar to select or unselect the software you wish to install. \
You can use the up and down arrows to see all the possible choices. \
Recommended choices have been preselected. \
Press the ENTER key when you are finished." >> $TMP/tmpscript
echo -n '" 20 80 9 "A" "' >> $TMP/tmpscript
gettext "Base Linux system" >> $TMP/tmpscript
echo -n '" on "' >> $TMP/tmpscript
gettext "The A (base) series contains the kernel and main system utilities." >> $TMP/tmpscript
echo -n '"' >> $TMP/tmpscript

if [ -d $DS/ap -o "$DS" = "" ]; then
echo -n ' "AP" "' >> $TMP/tmpscript
gettext "Various Applications that do not need X" >> $TMP/tmpscript
echo -n '" on "' >> $TMP/tmpscript
gettext "The AP series is a collection of useful applications." >> $TMP/tmpscript
echo -n '"' >> $TMP/tmpscript
fi

if [ -d $DS/d -o "$DS" = "" ]; then
echo -n ' "D" "' >> $TMP/tmpscript
gettext "Program Development (C, C++, Lisp, Perl, etc.)" >> $TMP/tmpscript
echo -n '" on "' >> $TMP/tmpscript
gettext "The D series contains compilers, debuggers, and other programming tools." >> $TMP/tmpscript
echo -n '"' >> $TMP/tmpscript
fi

if [ -d $DS/e -o "$DS" = "" ]; then
echo -n ' "E" "' >> $TMP/tmpscript
gettext "GNU Emacs" >> $TMP/tmpscript
echo -n '" on "' >> $TMP/tmpscript
gettext "The E series contains the GNU Emacs advanced real-time display editor." >> $TMP/tmpscript
echo -n '"' >> $TMP/tmpscript
fi

if [ -d $DS/f -o "$DS" = "" ]; then
echo -n ' "F" "' >> $TMP/tmpscript
gettext "FAQ lists, HOWTO documentation" >> $TMP/tmpscript
echo -n '" on "' >> $TMP/tmpscript
gettext "The F series contains essential documentation for Linux system administrators." >> $TMP/tmpscript
echo -n '"' >> $TMP/tmpscript
fi

if [ -d $DS/gnome -o "$DS" = "" ]; then
echo -n ' "GNOME" "' >> $TMP/tmpscript
gettext "The GNOME desktop for X" >> $TMP/tmpscript
echo -n '" on "' >> $TMP/tmpscript
gettext "The GNOME series contains the GNOME desktop environment and related libraries." >> $TMP/tmpscript
echo -n '"' >> $TMP/tmpscript
fi

if [ -d $DS/k -o "$DS" = "" ]; then
echo -n ' "K" "' >> $TMP/tmpscript
gettext "Linux kernel source" >> $TMP/tmpscript
echo -n '" on "' >> $TMP/tmpscript
gettext "The K series contains the source code for the Linux kernel." >> $TMP/tmpscript
echo -n '"' >> $TMP/tmpscript
fi

if [ -d $DS/kde -o "$DS" = "" ]; then
echo -n ' "KDE" "' >> $TMP/tmpscript
gettext "Qt and the K Desktop Environment for X" >> $TMP/tmpscript
echo -n '" on "' >> $TMP/tmpscript
gettext "The KDE series contains the K Desktop Environment and related libraries." >> $TMP/tmpscript
echo -n '"' >> $TMP/tmpscript
fi

if [ -d $DS/kdei -o "$DS" = "" ]; then
echo -n ' "KDEI" "' >> $TMP/tmpscript
gettext "International language support for KDE" >> $TMP/tmpscript
echo -n '" off "' >> $TMP/tmpscript
gettext "The KDEI series provides support for languages other than US English in KDE." >> $TMP/tmpscript
echo -n '"' >> $TMP/tmpscript
fi

if [ -d $DS/l -o "$DS" = "" ]; then
echo -n ' "L" "' >> $TMP/tmpscript
gettext "System Libraries (some needed by both KDE and GNOME)" >> $TMP/tmpscript
echo -n '" on "' >> $TMP/tmpscript
gettext "The L series contains libraries needed by GNOME, KDE, and other programs." >> $TMP/tmpscript
echo -n '"' >> $TMP/tmpscript
fi

if [ -d $DS/n -o "$DS" = "" ]; then
echo -n ' "N" "' >> $TMP/tmpscript
gettext "Networking (TCP/IP, UUCP, Mail, News)" >> $TMP/tmpscript
echo -n '" on "' >> $TMP/tmpscript
gettext "The N series contains network related clients and servers." >> $TMP/tmpscript
echo -n '"' >> $TMP/tmpscript
fi

if [ -d $DS/t -o "$DS" = "" ]; then
echo -n ' "T" "' >> $TMP/tmpscript
gettext "TeX typesetting software" >> $TMP/tmpscript
echo -n '" on "' >> $TMP/tmpscript
gettext "TeX is a typesetting system often used for mathematics and technical papers." >> $TMP/tmpscript
echo -n '"' >> $TMP/tmpscript
fi

if [ -d $DS/tcl -o "$DS" = "" ]; then
echo -n ' "TCL" "' >> $TMP/tmpscript
gettext "Tcl/Tk script languages" >> $TMP/tmpscript
echo -n '" on "' >> $TMP/tmpscript
gettext "The TCL series contains the Tcl/Tk/TclX languages and programs that use them." >> $TMP/tmpscript
echo -n '"' >> $TMP/tmpscript
fi

if [ -d $DS/x -o "$DS" = "" ]; then
echo -n ' "X" "' >> $TMP/tmpscript
gettext "X Window System" >> $TMP/tmpscript
echo -n '" on "' >> $TMP/tmpscript
gettext "This series contains X, the windowing system used by Linux." >> $TMP/tmpscript
echo -n '"' >> $TMP/tmpscript
fi

if [ -d $DS/xap -o "$DS" = "" ]; then
echo -n ' "XAP" "' >> $TMP/tmpscript
gettext "X Applications" >> $TMP/tmpscript
echo -n '" on "' >> $TMP/tmpscript
gettext "The XAP series is a collection of applications for X." >> $TMP/tmpscript
echo -n '"' >> $TMP/tmpscript
fi

if [ -d $DS/xfce -o "$DS" = "" ]; then
echo -n ' "XFCE" "' >> $TMP/tmpscript
gettext "The Xfce Desktop Environment for X" >> $TMP/tmpscript
echo -n '" on "' >> $TMP/tmpscript
gettext "Xfce is a fast and lightweight GTK+ based desktop environment for X." >> $TMP/tmpscript
echo -n '"' >> $TMP/tmpscript
fi

if [ -d $DS/y -o "$DS" = "" ]; then
echo -n ' "Y" "' >> $TMP/tmpscript
gettext "Games" >> $TMP/tmpscript
echo -n '" on "' >> $TMP/tmpscript
gettext "The Y series is a collection of classic BSD text-based games." >> $TMP/tmpscript
echo -n '"' >> $TMP/tmpscript
fi

echo -n "  2> $TMP/series" >>$TMP/tmpscript
. $TMP/tmpscript
if [ ! $? = 0 ]; then
  rm -rf $TMP/series $TMP/tmpscript
  exit
fi
INSTSETS="`cat $TMP/series | tr -d " "`"
INSTSETS="`echo $INSTSETS | tr "\042" "#" `"
INSTSETS="`echo $INSTSETS | tr "," "#" `"
INSTSETS="`echo $INSTSETS | tr -s "#" `"
rm -rf $TMP/series $TMP/tmpscript
echo "$INSTSETS" > $TMP/SeTSERIES
